language: python
matrix:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38

install:
  - pip install --upgrade numpy
  - pip install --upgrade numba
  - pip install --upgrade scipy
  - pip install --upgrade Cython
  - pip install --upgrade codecov
  - pip install --upgrade pytest-cov
  - pip install --upgrade -e .

script:
  - pytest --cov=bosonic tests

after_success:
  - codecov
